### ISSUE TITLE
Error on WSL

### ISSUE THREAD

**Issue by ThomasdenH** [LucianoBestia/cargo_crev_reviews_workspace#1]
I got an error on WSL that was solved by installing `xdg-utils`. I think it would be useful to provide a hint to do so on the following `unwrap()`:

https://github.com/LucianoBestia/cargo_crev_reviews_workspace/blob/e5ab54256362a926cda637dc5903c8a3e1f4c36d/cargo_crev_reviews/src/bin/cargo_crev_reviews.rs#L56

**Comment by LucianoBestia** [comment]
Thank you. 
I use Debian inside WSL2 and probably `xdg-open` was preinstalled:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
What distro do you use?

**Comment by LucianoBestia** [comment]
This project is a work in progress and I would like to hear more about how it works on other computers. There is a lot of assumption I make, that can go wrong in other systems. And I cannot test it all, because it would be a gigantic task. 
I appreciate some feedback.
Have you installed this program from crates.io? Or clone it from github and build it using `cargo auto`?
Thank you.

**Comment by LucianoBestia** [comment]
I added some lines to the README.md:  
## Code-flow

Everything is compiled into one single executable binary for Linux: `cargo_crev_reviews`.  
First it opens the default browser with `xdg-open` on <http://127.0.0.1:8182/cargo_crev_reviews/index.html>.  
I received a comment that `xdg-open` is not preinstalled on every Linux distro. I use Debian 10 and have it.  
On other distros it is possible to install it with `xdg-utils`.  
If your WSL2 does not have yet a default browser run this:

**Comment by LucianoBestia** [comment]
I added a descriptive error message with `except("")`:
```rust
/// open browser with xdg-open
pub fn open_browser() {
    // open default browser in Linux
    // for WSL2 in Win10 I used my project https://crates.io/crates/wsl_open_browser
    let x = std::process::Command::new("xdg-open")
        .arg(&format!(
            "http://{}:{}/{}/index.html",
            SERVER_HOST.as_str(),
            SERVER_PORT.as_str(),
            SERVER_FIRST_SUBDIRECTORY.as_str()
        ))
        .spawn()
        .expect("Failed to open browser using `xdg-open`. Probably it is not installed on your system. Try to instal it with `xdg-utils`.");
    drop(x);
}
```

**Comment by ThomasdenH** [comment]
Perfect! I had installed it with `cargo install`.

Feel free to close this issue!
